{% set name = "modflow-setup" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modflow-setup-{{ version }}.tar.gz
  sha256: d94e869ba7f14bac6e4dc586248e986ec9bc96d8078aa2f81f9f139373a43487

build:
  entry_points:
    - get-modflow = flopy.utils.get_modflow:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - pip
  run:
    - python >=3.11
    - geopandas
    - gis-utils
    - fiona
    - flopy
    - modflow-export
    - netcdf4
    - numpy
    - pandas
    - pyproj
    - pyyaml
    - rasterio
    - rasterstats
    - rtree
    - scipy
    - sfrmaker
    - shapely
    - xarray

test:
  imports:
    - mfsetup
  commands:
    - pip check
    - get-modflow --help
  requires:
    - pip

about:
  home: https://github.com/DOI-USGS/modflow-setup.git
  summary: Rapid and robust construction of MODFLOW groundwater flow models
  license: CC0-1.0
  license_file: LICENSE.md
  doc_url: https://doi-usgs.github.io/modflow-setup/latest/

extra:
  recipe-maintainers:
    - aleaf
    - jdhughes-usgs
