{% set python_min = "3.11" %}
{% set name = "modflow-setup" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1505bee3cea7f299988ffb9d5c8f02a8c763221318cdc25841df8f8c065ea11e

build:
  entry_points:
    - get-modflow = flopy.utils.get_modflow:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - gis-utils
    - fiona
    - flopy
    - modflow-export
    - netcdf4
    - numpy
    - pandas
    - pyproj
    - pyyaml
    - rasterio
    - rasterstats
    - rtree
    - scipy
    - sfrmaker
    - shapely
    - xarray

test:
  imports:
    - mfsetup
  commands:
    - pip check
    - get-modflow --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DOI-USGS/modflow-setup.git
  summary: Rapid and robust construction of MODFLOW groundwater flow models
  license: CC0-1.0
  license_file: LICENSE.md
  doc_url: https://doi-usgs.github.io/modflow-setup/latest/

extra:
  recipe-maintainers:
    - aleaf
    - jhughes-dev
